services:
  - type: web
    name: freshrss
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./freshrss/Docker/Dockerfile
    dockerContext: ./freshrss
    envVars:
      - fromGroup: freshrss-settings
      
databases:
  - name: freshrssdb
    databaseName: freshrss    
    region: frankfurt
    plan: free
    
envVarGroups:
  - name: freshrss-settings
    envVars:
      - key: ADMIN_EMAIL
        sync: false
