services:
  - type: web
    name: freshrss
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./freshrss/Docker/Dockerfile
    dockerContext: ./freshrss
    envVars:
      - fromGroup: conc-settings
      - key: BASE_URL
        fromService:
          name: freshrss
          type: web
          property: host
      - key: DB_HOST
        fromDatabase:
          name: freshrssdb
          property: host
      - key: DB_USER
        fromDatabase:
          name: freshrssdb
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: freshrssdb
          property: password
      - key: DB_BASE
        fromDatabase:
          name: freshrssdb
          property: database
      
databases:
  - name: freshrssdb
    databaseName: freshrss    
    region: frankfurt
    plan: free
    
envVarGroups:
  - name: conc-settings
    envVars:
      - key: ADMIN_API_PASSWORD
        generateValue: true
      - key: ADMIN_EMAIL
        sync: true
      - key: ADMIN_PASSWORD
        generateValue: true
